# the processing team appearently can't get a good CMD-line tool together.
# Hence, I am forced to do this trickery...
# Replace the processing-java path with your path
default:
	~/Downloads/processing-4.1.1/processing-java --sketch=./feigenbaum --run
